### ISSUE TITLE
HTTPClient::TimeoutError should subclass ::TimeoutError

### ISSUE THREAD

**Issue by kstephens** [nahi/httpclient#35]
Here's the scenario.  Older code wrapped HTTPClient with a ::Timeout.timeout, but HTTPClient is handing it's own timeouts:

    def my_method
      Timeout.timeout(120) do
        some_deep_method
      end
    rescue ::Timeout => err
      take_evasive_action
    end
    def some_deep_method
      result = HTTPClient....
      process result
    end

If HTTPClient's internal timeout mechanism raises a HTTPClient::ReceiveTimeoutError before the outer ::Timeout.timeout(), ReceiveTimeoutError is thrown, which *is not* a subclass of ::TimeoutError, thus take_evasive_action is never called and the exception is never caught.

The set of exceptions thrown by an API are a part of the API --- ReceiveTimeoutError is not a ::TimeoutError, thus the API was changed.

The fix is:

    # httpclient.rb
    ...
    require 'timeout'
    ...
    class HTTPClient
      ...
      class TimeoutError < ::TimeoutError ; end
      ...
    end

This fix should be backwards- and forwards- compatible.

**Comment by nahi** [comment]
I close this issue as "Wont' fix" because it's a "BUG" that introduced incompatible change to API as original reporter stated. But I still am thinking that it's required change (::Timeout::Error == ::TimeoutError must be handled only by timeout library, not by others) so I cannot revert the change (I cannot change ReceiveTimeout, etc. to a subclass of ::TimeoutError.)

Since this API incompatible BUG lasted over 3 years I assume this change was accepted.
