### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by xuanxu** [nahi/httpclient#464]
Hey @nahi! 👋 
Any plan to push httpclient 2.8.4 or 2.9 to Rubygems? 
A new release including the recent dependency changes to remove Ruby 3.X warnings would be very welcome 🙏

**Comment by xuanxu** [comment]
cc/ @takkanm @shaper

**Comment by takkanm** [comment]
@xuanxu Thank you for your mention. I understand what you asked for.

The following is my opinion.

It's been almost eight years since our last release, and we don't have CI.
In addition, I haven't passed the test with Ruby3.4-preview2.

If we were to release a new version, we would wait until after we can pass testing with 3.4, which will be released in December.

I know releasing a new version is best. 
However, if warnings are the only problem, a quick solution would be temporarily adding a dependency on `mutex_m` on your gem or application side.

Sorry to bother you.

**Comment by xuanxu** [comment]
@takkanm I didn't consider the lack of CI, you are right, waiting to pass tests with 3.4 sounds good. 
Thank you for your quick response!
